server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: admin-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:1380}/eureka/