server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:1380}/eureka/

spring:
  application:
    name: hystrix-gateway
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: true

  endpoint:
    hystrix:
      stream:
        enabled: true