server:
  port: 1380

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:1380/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411/