server:
  port: ${SERVER_PORT:1111}

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:1380}/eureka/

spring:
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}/

  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"