server:
  port: 1379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1380/eureka/

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  zipkin:
    base-url: http://localhost:9411/

ispark:
  url: https://api.ibb.gov.tr/ispark
