server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:1380}/eureka/

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}/


  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8080}

ispark:
  url: 'https://api.ibb.gov.tr/ispark'

management:
  endpoints:
    web:
      exposure:
        include: "*"