server:
  port: ${SERVER_PORT:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:1380}/eureka/

spring:
  rabbitmq:
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASS}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true
          timeout: 5000

  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8080}

  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}/

management:
  endpoints:
    web:
      exposure:
        include: "*"