server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/microservice
        bootstrap: true
      enabled: true
  application:
    name: config-server
  profiles:
    active: native
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}/
